version: "3.9"
services:
  api:
    image: node:20-alpine
    working_dir: /app
    command: sh -c "npm i && npm run dev"
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development
      - PORT=3000
